version: '3.8'

networks:
  proxy_net:
    driver: overlay

services:
  
  passer:
    image: passer:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: "2048MB"
    networks:
      - proxy_net
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    networks:
      - proxy_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:r
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: "2048MB"
    depends_on:
      - servidor

  servidor:
    image: servidor:latest
    networks:
      - proxy_net
    deploy:
      replicas: 3  # Número de réplicas (podem ser ajustadas)
      resources:
        limits:
          cpus: '1'
          memory: 512MB
    restart: always
    
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    networks:
      - proxy_net
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - nginx

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3001:3000"
    networks:
      - proxy_net
  
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - proxy_net
  
  autoscaler:
    image: autoscaler:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_net
    deploy:
      placement:
        constraints:
          - node.role == manager

