networks:
  proxy_net:
    driver: bridge

services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy
    ports:
      - 3000:3000
    networks:
      - proxy_net
    depends_on:
      - servidor1
      - servidor2
      - servidor3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  servidor1:
    container_name: servidor1
    build:
      context: ./server
    networks:
      - proxy_net
    deploy:
      resources:
        limits:
          cpus: '.1'
          memory: 512MB
        reservations:
          cpus: '0'
          memory: 0MB

  servidor2:
    container_name: servidor2
    build:
      context: ./server
    networks:
      - proxy_net
    deploy:
      resources:
        limits:
          cpus: '.1'
          memory: 512MB
        reservations:
          cpus: '0'
          memory: 0MB

  servidor3:
    container_name: servidor3
    build:
      context: ./server
    networks:
      - proxy_net
    deploy:
      resources:
        limits:
          cpus: '.1'
          memory: 512MB
        reservations:
          cpus: '0'
          memory: 0MB
